### PR TITLE
extend journey to alternately use PostgreSQL for Compose as Bluemix Service

### PR DESCRIPTION
**Pull request by timroster**
Match environment variables in postgres.yaml to those used in db-setup script

Update entrypoint.sh script for gitlab container to pull credentials from a kubernetes secret containing credentials for a Bluemix service. Keep database creation in postgres container for the three container scenario, but move database creation into entrypoint.sh when using PostgreSQL for Compose. Clarify parameters used in psql call to use input environment variables.

Add alternate set of steps and link from main README.md. Add separate gitlab deployment file and quickstart for using PostgreSQL for Compose.

### CODE REVIEW

**Comment by animeshsingh** [comment]
LGTM.  @rmoe Tim is proposing a PR to also be able to use Compose Postgre in addition to Postgre docker image. Please review and merge if its good to you

**Comment by animeshsingh** [comment]
@Tomcli please review it as well

**Comment by Tomcli** [comment]
In your gitlab-postgres-svc.yaml file, you should add the environment variable for your db-host
- name: DB_HOST
   value: binding-compose-for-postgresql-gl

Otherwise, gitlab won't see postgreSQL as its database

**Comment by timroster** [comment]
DB_HOST is intentionally blank. This will vary for each different instance of Compose for PostgreSQL that is bound to the cluster. Unfortunately, the credentials as bound with bx cs cluster-bind are not trivially mappable to env variables. So code at start of entrypoint.sh tests for the presence of the credentials file, then parses it and assigns DB_HOST and other parameters.

**Comment by Tomcli** [comment]
Never mind, everything works fine for me after rebinding the service.

**Pull request merged**
