### PR TITLE
fix for gitlab-ce images using postgresql on Bluemix

### PR DESCRIPTION
**Pull request by timroster**
With the change to docker hub gitlab-ce images, the credentials for the PostgreSQL db on Bluemix need to be managed directly into the deployment file as deployment that requires parsing kubernetes secrets won't work without a custom entrypoint.sh.

Update README and gitlab-postgres-svc.yaml file.

### CODE REVIEW

**Comment by animeshsingh** [comment]
Thanks @timroster 
@paulczar since it fixes the PR you submitted - please have a look
@Tomcli also check once

**Comment by Tomcli** [comment]
LGTM. I think it could be more clarify if we can add some comments above the values that we want to replace in the yaml file.

**Comment by animeshsingh** [comment]
@timroster can @Tomcli suggestion be a quick fix for you?

**Comment by timroster** [comment]
@animeshsingh put something in above each field. @Tomcli lmk if better.

**Comment by Tomcli** [comment]
Yeah it looks great to me.

**Pull request merged**
