### PR TITLE
[WIP] fix gitlab install on s390x

### PR DESCRIPTION
**Pull request by loafyloaf**
this PR should have gitlab actually installing on a s390x system

### CODE REVIEW

**Comment by animeshsingh** [comment]
@loafyloaf does this get GitLab running with distributed mode on, where GitLab-Postgres and Redis are all on their won cotnainers? Alao any insight on what you changed and why?

**Comment by animeshsingh** [comment]
Also does this mean we can not run this on RH host?

**Comment by loafyloaf** [comment]
@animeshsingh The changes to `Dockerfile-gitlab` imitate the steps I had to take to get gitlab installed on a blank ubuntu s390x instance, mostly to work around a bug (https://bugs.launchpad.net/ubuntu/+source/gitlab/+bug/1574349) in the package.  The PR also contains the slightly modified version of docker-compose.yml from the root of this repo I am using.  Still testing to see if the docker images interact correctly...

**Comment by animeshsingh** [comment]
Ok - lets keep this is waiting stage - lets shoot to extend this PR to which actually gets the GitLab 'workload' running as a whole, rather then individual components

**Pull request closed without merging**
