### PR TITLE
update to use upstream gitlab-ce images

### PR DESCRIPTION
**Pull request by paulczar**
* remove containers/*
* move k8s manifests to kubernetes/
* update docs to reflect changes
* update scripts to reflect changes
* move auxillary docs to docs/

### CODE REVIEW

**Comment by animeshsingh** [comment]
LGTM - except for pointing to Bluemix docs for setting up cluster etc. Docs shows a lot more things than just setting up CLI, and user can wander. I would want this to be focussed through github that they create cluster and move forward, and remain in github.

@rmoe Please go through it once.

**Comment by paulczar** [comment]
Makes sense, I was concerned that our docs could get stale if functionality changes upstream, for instance you no longer need the cloud foundry client which the original link says to download and the bluemix docs no longer do.

Happy to flip it back to the original link if we prefer.

**Comment by animeshsingh** [comment]
Yes - that`s what we give with that, but as long as we keep it as concise as we need, tradeoff will be worth it. We have planned to do periodic updates of CLI instructions.

**Comment by paulczar** [comment]
updated!

**Comment by animeshsingh** [comment]
Thanks Paul. @Tomcli Please provide on test run at your end, and if all is good I will merge.

**Comment by Tomcli** [comment]
Since we are using nodePort, the external URL for gitlab won't work for us. So, in your `using-gitlab.md`, you should change the command `git clone ssh://git@gitlab.example.com:30022/<user>/<project name>` to `git clone ssh://git@<node IP>:30022/<user>/<project name>`

Everything else looks good and is working for me.

**Comment by paulczar** [comment]
@Tomcli you'll see in the doc I specify to set `gitlab.example.com` in etc/hosts if they want to use the url ( that way the urls provided by gitlab web-ui work ) otherwise to use the IP.

here you can see the ssh connecting fine and getting denied because of no pub key:

```
ssh -p 30022 git@gitlab.example.com
The authenticity of host '[gitlab.example.com]:30022 ([169.48.131.102]:30022)' can't be established.
ECDSA key fingerprint is SHA256:b1PatTcFgWBugKuzspphEF/DUfYRIKoZMdwedjqLgAg.
Are you sure you want to continue connecting (yes/no)? yes
Permission denied (publickey).
```

**Comment by Tomcli** [comment]
I see. Maybe we could add an example (<Node IP>:30022) to clarify what the user should do when they don't want to put the URL in their hosts file.

**Comment by animeshsingh** [comment]
I will merge this, and open node port example as an issue for Paul

**Pull request merged**
